---

- name: Add repository for PHP 7.1
  apt_repository:
    repo: ppa:ondrej/php
    state: present

- name: Install common packages
  apt:
    pkg: '{{ item }}'
    state: present
    update_cache: yes
  become: yes
  become_method: sudo
  with_items:
    - language-pack-de
    - curl
    - wget
    - make
    - rsync
    - vim
    - unzip
    - git
    - nodejs
    - nodejs-legacy
    - php7.1
    - php7.1-cli 
    - php7.1-common 
    - php7.1-mbstring 
    - php7.1-gd 
    - php7.1-intl 
    - php7.1-xml 
    - php7.1-mysql 
    - php7.1-mcrypt 
    - php7.1-zip
    - php7.1-curl
    - php7.1-bcmath
    - php7.1-bz2
  tags:
    - common

- name: Install Grunt
  npm:
    name: grunt
    global: yes
    state: present
  become: yes
  become_method: sudo

- name: Disable firewall
  shell: ufw disable
  become: yes
  become_method: sudo
  tags:
    - common

- name: Stop firewall and flush rules
  shell: '{{ item }}'
  become: yes
  become_method: sudo
  with_items:
    - iptables -t nat -F
    - iptables -t nat -X
    - iptables -t mangle -F
    - iptables -t mangle -X
    - iptables -P INPUT ACCEPT
    - iptables -P FORWARD ACCEPT
    - iptables -P OUTPUT ACCEPT
  tags:
    - common

- name: Change /etc/hosts
  template: src=hosts.tpl dest=/etc/hosts
  become: yes
  become_method: sudo
  tags:
    - common
