- name: Copy ssh key into VM
  template: src={{ item.name }} dest=/home/vagrant/.ssh/{{ item.name }} owner=vagrant group=vagrant mode={{ item.mode }}
  with_items:
    - name: "id_rsa"
      mode: "0600"
    - name: "id_rsa.pub"
      mode: "0644"
  become: yes
  become_method: sudo
  tags:
    - hulk-avency-com

- name: Add custom repository server to known_hosts
  known_hosts:
    host="{{ item.host }}"
    key="{{ item.publicKey}}"
  with_items:
    - host: hulk.avency.com
      publicKey: "hulk.avency.com ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDVzDp9m3cpJGVd3boG0tYAo+mHtIQO4TkBiX+iVZBVS5HNPnvNTsJhjBcunHZmI6cMlBuMKs1qz6PXqDSQ7ob2qghPy8UiEhBEutNqvy2P3u80MWi9I/yXxCkiUtIi3vg9Pm2QyMXincle3XD1zHtguRmZVgI325LgCd4jv+pR4RfwqY/RgML38us5HgOrbNWkDZNOuAQjtw+Yqm2tGHyW8NzClYh/vOBGgBe89cBff57hyhw9NqBhaUMyTMOIBXIkLrsNuwmiFiKa+O9nZh2plq6qzlRDuaEltAaPbCBJoqYPccfylqb0x4hn2/NuTIT423dQQiOHDk8BzHyq6uhh"
    - host: 192.168.0.216
      publicKey: "192.168.0.216 ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDVzDp9m3cpJGVd3boG0tYAo+mHtIQO4TkBiX+iVZBVS5HNPnvNTsJhjBcunHZmI6cMlBuMKs1qz6PXqDSQ7ob2qghPy8UiEhBEutNqvy2P3u80MWi9I/yXxCkiUtIi3vg9Pm2QyMXincle3XD1zHtguRmZVgI325LgCd4jv+pR4RfwqY/RgML38us5HgOrbNWkDZNOuAQjtw+Yqm2tGHyW8NzClYh/vOBGgBe89cBff57hyhw9NqBhaUMyTMOIBXIkLrsNuwmiFiKa+O9nZh2plq6qzlRDuaEltAaPbCBJoqYPccfylqb0x4hn2/NuTIT423dQQiOHDk8BzHyq6uhh"
  become: yes
  become_user: vagrant
  tags:
    - hulk-avency-com