---

- name: Install required packages
  apt:
    pkg: python-setuptools
    state: present
    update_cache: yes
  become: yes
  become_method: sudo
  tags:
    - docker-compose

- name: Installing dependencies
  easy_install:
    name: pip
  become: yes
  become_method: sudo
  tags:
    - docker-compose

- name: Installing docker compose
  pip:
    name: docker-compose
    state: present
  become: yes
  become_method: sudo
  tags:
    - docker-compose
