---

- stat: path=/usr/bin/docker
  register: dockerConfigured
  tags:
    - docker

- name: Install docker GPG key
  shell: curl -fsSL https://get.docker.com/gpg | sudo apt-key add -
  when: not dockerConfigured.stat.exists
  become: yes
  become_method: sudo
  tags:
    - docker

- name: Install docker
  shell: curl -sSL https://get.docker.com/ | sh
  when: not dockerConfigured.stat.exists
  become: yes
  become_method: sudo
  tags:
    - docker

- name: Start Docker service
  service: name=docker state=started
  when: not dockerConfigured.stat.exists
  become: yes
  become_method: sudo

- name: create folder
  file:
    path: '{{ docker.directory }}'
    state: directory
    mode: 0775
    group: vagrant
    owner: vagrant
  when: not dockerConfigured.stat.exists
  become: yes
  become_method: sudo

- name: start docker when server boots
  shell: update-rc.d docker defaults
  when: not dockerConfigured.stat.exists
  become: yes
  become_method: sudo
  tags:
    - docker

- name: Install docker compose
  pip: name=docker-compose
  when: not dockerConfigured.stat.exists
  become: yes
  become_method: sudo
  tags:
    - docker

- name: Add vagrant user to docker group
  shell: usermod -aG docker vagrant
  when: not dockerConfigured.stat.exists
  become: yes
  become_method: sudo
  tags:
    - docker

- name: Add docker0 bridge to iptables
  shell: iptables -t nat -N DOCKER && iptables -t nat -A PREROUTING -m addrtype --dst-type LOCAL -j DOCKER && iptables -t nat -A PREROUTING -m addrtype --dst-type LOCAL ! --dst 127.0.0.0/8 -j DOCKER
  when: not dockerConfigured.stat.exists
  become: yes
  become_method: sudo
  tags:
    - docker

- name: Run abh1nav/dockerui:latest container
  shell: docker run -d -p 9000:9000 -v /var/run/docker.sock:/docker.sock --name dockerui abh1nav/dockerui:latest -e="/docker.sock"
  ignore_errors: yes
  become: yes
  become_method: sudo
  tags:
    - docker