---

# @todo: Check if the path is correct for docker-ce
- name: Check if docker is already installed
  stat: path=/usr/bin/docker
  register: dockerConfigured
  tags:
    - docker

- name: Install recommended extra packages for trusty 14.04
  apt:
    pkg: '{{ item }}'
    state: present
    update_cache: yes
  become: yes
  become_method: sudo
  with_items:
    - linux-image-extra-$(uname -r)
    - linux-image-extra-virtual
    - apt-transport-https
    - ca-certificates
    - curl
    - software-properties-common
  tags:
    - docker

- name: Add Docker's official GPG key
  shell: curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
  become: yes
  become_method: sudo
  tags:
    - docker

- name: Setup a stable repository
  shell: add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
  become: yes
  become_method: sudo
  tags:
    - docker

- name: Install docker-ce
  apt:
    pkg: '{{ docker-ce }}'
    state: present
    update_cache: yes
  become: yes
  become_method: sudo
  tags:
    - docker

- name: Create docker folder
  file:
    path: '{{ docker.directory }}'
    state: directory
    mode: 0775
    group: vagrant
    owner: vagrant
  when: not dockerConfigured.stat.exists
  become: yes
  become_method: sudo

- name: Configuring service
  service:
    name: docker
    enabled: "yes"
    state: "present"

- name: Add vagrant user to docker group
  shell: usermod -aG docker vagrant
  when: not dockerConfigured.stat.exists
  become: yes
  become_method: sudo
  tags:
    - docker
